### ISSUE TITLE
Manuális kód átvizsgálás elvégzése

### ISSUE THREAD

**Issue by R0leeX** [BME-MIT-IET/DAJC-iet-2019#13]
#### Steps to reproduce the behaviour
1. 

#### Software specifications
* GnuCash Android version:
* System Android version:
* Device type:

**Comment by urbno** [comment]
A kódot átvizsgáltuk, AndroidStudioban sikeresen lebuildelődik, továbbá konzolban is. Sonarqube-al sikeresen tudtuk elemezni a kódot, több hibát javítottunk is, sajnos azonban a Travis nem akart lefutni
